Repository AllDayAlone/summer, pull requests merged in 2020-07, with the labels that each got.

#44 Add "inRange" function solution
  src/inRange.js
Labels: to review

#59 escape function solution
  src/escape.js
Labels: to review

#58 Initial function
  src/initial.js
  test/initial.spec.js
Labels: to review

#57 Map
  src/map.js
Labels: to review

#56 add feature
  repArr.js
Labels: to review

#55 add solution of task add tail finction
  solution_task/index.js
Labels: changes requested

#51 Map values
  src/mapValues.js
  test/mapValues.spec.js
Labels: to review

#50 Add dropRight function solution
  src/dropRight.js
Labels: to review

#21 head (tail) function
  src/tail.js
  test/tail.spec.js
Labels: changes requested

#43 add feature
  utils/drop.js
Labels: changes requested

#46 Median function
  src/median.js
Labels: changes requested

#47 Add sortedUniq function
  .gitignore
  src/sortedUniq.js
  test/sortedUniq.spec.js
Labels: bug, changes requested
